User documentation - Inbox
simplic/documentation pull request #114
Opened 2021-10-21 13:44 UTC by AEichhoff

2021-12-03 20:03 UTC, MEichhoff requested changes

2021-12-03 20:03 UTC, MEichhoff commented on user/DMS/Inbox/Posteingang.md
> +Hierzu wird zuerst das erste Dokument ausgewählt und im Menu die Funktion Neuer Stapel ausgewählt.
```suggestion
Hierzu wird zuerst das erste Dokument ausgewählt und im Menü die Funktion Neuer Stapel ausgewählt.
```

2021-12-03 20:03 UTC, MEichhoff commented on user/DMS/Inbox/Posteingang.md
> +Bei geöffnetem Fenster, wird ein weiters Dokument - egal ob im Posteingang oder in der Dokumentenverwaltung - mit dem Menue Eintrag "Zum Stapel hinzufügen" hinzugefügt.
```suggestion
Bei geöffnetem Fenster wird ein weiters Dokument - egal ob im Posteingang oder in der Dokumentenverwaltung - mit dem Menüeintrag "Zum Stapel hinzufügen" hinzugefügt.
```

2021-12-03 20:06 UTC, MEichhoff commented
Außerdem fällt auf dass du manchmal den Namen von Menüfunktionen in Anführungszeichen schreibst und manchmal nicht. Einheitlich wäre es wahrscheinlich besser.

2021-12-04 13:50 UTC, simplicbe commented
@AEichhoff please commit Marvins suggestions. Please keep in mind that this repository is public

2021-12-06 07:13 UTC, AEichhoff commented on user/DMS/Inbox/Posteingang.md
> +Der Posteingang bildet den Dokumenteneingang in das Unternehmen ab.
Nee abbilden und nicht darbilden! Abgelehnt!

2021-12-06 07:18 UTC, merged