Add the Create List into the documentation (~2447)
simplic/documentation pull request #125
Opened 2022-02-03 13:21 UTC by MaxPatyk

2022-03-25 11:24 UTC, MEichhoff requested changes
Cosa vogliono dirmi

2022-05-12 09:34 UTC, TM-Simplic requested changes

2022-05-12 09:34 UTC, TM-Simplic commented on support/Misc/Forms/forms.md
> +With a right click on a "List Field" the user can create a Child Field, when the user clicks "Neues Feld".
```suggestion
To create a child field the user clicks on "Neues Feld" inside the context menu, which is opened by right clicking on a "List Field".
```

2022-05-12 09:34 UTC, TM-Simplic commented on support/Misc/Forms/forms.md
> +If the user will update a Field, then clicks "Feld bearbeiten".
```suggestion
To change a child field the user clicks on "Feld bearbeiten" inside the context menu.
```

2022-05-12 09:34 UTC, TM-Simplic commented on support/Misc/Forms/forms.md
> +When a Field is unnecessary then the user clicks "Null-Werte zulassen", so the Field can be empty.
```suggestion
When a Field is not required the user enables "Null-Werte zulassen", so the field can be empty.  
```

2022-05-12 09:34 UTC, TM-Simplic commented on support/Misc/Forms/forms.md
> +The user clicks in the Property "Columns" the button "..." and can add Columns to the Grid.
```suggestion
Clicking on the "..." button for the property "Columns" the user can add columns to the grid.  
```

2022-05-12 09:34 UTC, TM-Simplic commented on support/Misc/Forms/forms.md
> +When the user clicks "Tabelle hinzufügen/bearbeiten" a new Database table will be create.
```suggestion
When the user clicks "Tabelle hinzufügen/bearbeiten" a new Database table will be created.  
```

2022-05-17 08:19 UTC, TM-Simplic approved these changes

2022-05-17 10:31 UTC, MEichhoff approved these changes

2022-05-17 11:17 UTC, merged