Adds bughunt page with tools placeholder.
simplic/documentation pull request #127
Opened 2022-05-11 10:30 UTC by TM-Simplic

2022-05-12 06:32 UTC, MaxPatyk commented on dev/bug_hunt/general_approach.md
> +- Priotize your possible error cases by effort, knowhow & likelyhood
```suggestion
- Prioritize your possible error cases by effort, knowhow & likelyhood
```

2022-05-12 06:44 UTC, MaxPatyk requested changes

2022-05-12 06:44 UTC, MaxPatyk commented on dev/bug_hunt/general_approach.md
> +Giving priority to cases that take little effort, don't need specific knowhow and have a high likelyhood of fixing the problem will increase the efficency of your bug hunt.
```suggestion
Giving priority to cases that take little effort, don't need specific knowhow and have a high likelihood of fixing the problem will increase the efficency of your bug hunt.
```

2022-05-12 06:44 UTC, MaxPatyk commented on dev/bug_hunt/general_approach.md
> +Starting with the most time consuming proble, you have no idea about is a terrible idea.
```suggestion
Starting with the most time consuming problem, you have no idea about is a terrible idea.
```

2022-05-12 06:44 UTC, MaxPatyk commented on dev/bug_hunt/general_approach.md
> +Sometimes they won't know how to fix it either but nontheless you should inform them after finding the problems solution without them.
```suggestion
Sometimes they won't know how to fix it either but nonetheless you should inform them after finding the problems solution without them.
```

2022-05-12 06:44 UTC, MaxPatyk commented on dev/bug_hunt/general_approach.md
> +Another good option is search for other with a similar or the same problem. If you have a specific error code search for tha in combination with the tool you are using.
```suggestion
Another good option is search for other with a similar or the same problem. If you have a specific error code search for that in combination with the tool you are using.
```

2022-05-12 08:56 UTC, TM-Simplic commented on dev/bug_hunt/general_approach.md
> +- What should have happend?
```suggestion
- What should happen?
```

2022-05-16 08:10 UTC, MEichhoff approved these changes

2022-05-16 10:33 UTC, MaxPatyk approved these changes

2022-05-17 08:20 UTC, merged